apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: s1-agent
  namespace: sentinelone
spec:
  releaseName: s1-agent
  targetNamespace: sentinelone
  install:
    createNamespace: true
  chart:
    spec:
      chart: s1-agent
      version: "25.4.2" # Matches your requested version
      sourceRef:
        kind: HelmRepository
        name: sentinelone
        namespace: flux-system
  interval: 10m
  values:
    secrets:
      # It is safer to use a Kubernetes Secret for this value
      # but for a direct translation of your command:
      site_key:
        value: "eyJ1cmwiOiAiaHR0cHM6Ly91c2VhMS1wdXJwbGUuc2VudGluZWxvbmUubmV0IiwgInNpdGVfa2V5IjogIjU2NTUyMDFlZTU1NWYwNmIifQ=="
      imagePullSecret: sentinelone-pull-secret
    configuration:
      cluster:
        name: cesar-flux
      inventory_only: false
      env:
        admission_controllers:
          validating:
            enabled: true
        helper:
          inventory_enabled: true
      repositories:
        agent: containers.sentinelone.net/cws-agent/s1agent
        helper: containers.sentinelone.net/cws-agent/s1helper
      tag:
        agent: 25.4.2-ga
        helper: 25.4.2-ga
      configuration:
        overrideConf:
         detectors:
           execute_from_memfd_lua:
            enabled: true
            verdict: silent
